'use strict';
const fs=require('node:fs'),path=require('node:path'),z=require('node:zlib'),rl=require('node:readline'),crypto=require('node:crypto'),{once}=require('node:events');
const {atomicJSON}=require('../store'),DAY=86400000;
const latestEnd=now=>Math.floor((now+3600000)/DAY)*DAY-3600000;
const dayName=end=>new Date(end+8*3600000).toISOString().slice(0,10);
async function digest(file){const h=crypto.createHash('sha256');for await(const c of fs.createReadStream(file))h.update(c);return h.digest('hex');}
async function buildArchive(dataDir,outputDir,end=latestEnd(Date.now())){const start=end-DAY;fs.mkdirSync(outputDir,{recursive:true});const file=path.join(outputDir,'analysis.jsonl.gz'),gzip=z.createGzip(),dest=fs.createWriteStream(file+'.tmp'),completed=new Promise((resolve,reject)=>{dest.on('finish',resolve);dest.on('error',reject);gzip.on('error',reject);});gzip.pipe(dest);const counts={},arms={},unknown={};let records=0;const write=async r=>{if(!gzip.write(JSON.stringify({dataset:'trend',record:r})+'\n'))await once(gzip,'drain');};
 for(const name of fs.readdirSync(dataDir).filter(n=>/^trend-\d{4}-\d{2}-\d{2}\.jsonl$/.test(n)).sort())for await(const line of rl.createInterface({input:fs.createReadStream(path.join(dataDir,name)),crlfDelay:Infinity})){if(!line.trim())continue;const r=JSON.parse(line);if(!(r.at>=start&&r.at<end))continue;await write(r);records++;counts[r.type]=(counts[r.type]||0)+1;if(r.type==='shadow_exit'){const a=arms[(r.strategy||"legacy")+":"+r.arm]??={closed:0,wins:0,net:0};a.closed++;a.wins+=r.netPnlSol>0?1:0;a.net+=r.netPnlSol;}if(r.type==='shadow_unknown')unknown[r.reason]=(unknown[r.reason]||0)+1;}
 gzip.end();await completed;fs.renameSync(file+'.tmp',file);const summary={schema:1,strategy:'mixed_strategy_window',window:{start:new Date(start).toISOString(),endExclusive:new Date(end).toISOString()},records,counts,arms,unknown,bytes:fs.statSync(file).size,sha256:await digest(file),notes:'Independent research arms; unknown outcomes excluded, not zero. Entries include signal/entry timestamps and frozen breakout level. Raw price is SOL per raw token. USD is provider-cached estimate; see record strategy and source.'};atomicJSON(path.join(outputDir,'summary.json'),summary);return summary;}
module.exports={digest,buildArchive,latestEnd,dayName,DAY,atomicJSON};
