'use strict';
const {WSOL}=require('./config'),{parseSwaps}=require('./parser');
class Discovery{
 constructor(c,store,rpc){this.c=c;this.store=store;this.rpc=rpc;this.price=null;this.queue=new Map();this.busy=false;this.nextPrice=0;}
 migration(e){if(!e.pool||!e.mint||!Number.isFinite(e.migrationAt)||e.migrationAt>Date.now()+2000)return;const old=this.store.data.ages[e.pool];if(old&&old.migrationAt!==e.migrationAt){this.store.log('age_conflict',{pool:e.pool});return;}this.store.data.ages[e.pool]={mint:e.mint,migrationAt:e.migrationAt,observedAt:Date.now(),signature:e.signature,source:'authenticated_pump_migration'};this.queue.delete(e.pool);this.store.log('migration_evidence',e);}
 old(pool,mint,now){const a=this.store.data.ages[pool];return !!(a&&a.mint===mint&&now-a.migrationAt>=this.c.minAgeMs);}
 request(pool,mint){if(this.store.data.ages[pool]||this.queue.has(pool)||this.queue.size>=100)return;this.queue.set(pool,{pool,mint,pages:0,before:null,scan:[],next:0});}
 async tick(){if(this.busy)return;this.busy=true;try{const now=Date.now();if(now>=this.nextPrice){this.nextPrice=now+60000;try{const r=await this.rpc.call('getAsset',{id:WSOL,options:{showFungible:true}}),p=r?.token_info?.price_info;if(!p||!['USD','USDC'].includes(p.currency)||!(p.price_per_token>0))throw new Error('price_unavailable');this.price={usd:p.price_per_token,fetchedAt:now,source:'helius_das',upstreamCacheMaxMs:600000};this.store.log('sol_usd',this.price);}catch{this.store.log('price_unavailable');}return;}const q=[...this.queue.values()].find(q=>q.next<=now);if(!q)return;q.next=now+10000;try{if(q.scan.length){const sig=q.scan.shift();const tx=await this.rpc.call('getTransaction',[sig,{encoding:'json',commitment:'confirmed',maxSupportedTransactionVersion:0}]);if(tx)parseSwaps({signature:sig,slot:tx.slot,receivedAt:now,transaction:tx},e=>{if(e.pool===q.pool&&e.mint===q.mint)this.migration(e);});if(!q.scan.length&&!this.store.data.ages[q.pool]){this.store.log('age_unavailable',{pool:q.pool,reason:'no_authenticated_migration'});q.next=now+86400000;}return;}if(q.pages>=this.c.maxAgePages){this.store.log('age_unavailable',{pool:q.pool,reason:'history_page_limit'});q.next=now+86400000;return;}const list=await this.rpc.call('getSignaturesForAddress',[q.pool,{limit:1000,...(q.before?{before:q.before}:{}),commitment:'confirmed'}]);q.pages++;if(!Array.isArray(list))throw new Error('invalid_signatures');if(list.length){q.oldest=list.filter(r=>!r.err).slice(-8).reverse().map(r=>r.signature);q.before=list.at(-1).signature;}if(list.length<1000){q.scan=q.oldest||[];if(!q.scan.length)q.next=now+86400000;}}catch{this.store.log('age_lookup_retry',{pool:q.pool});q.next=now+60000;}}finally{this.busy=false;}}
 usablePrice(now){return this.price&&now-this.price.fetchedAt<=120000?this.price:null;}
}
module.exports=Discovery;
