'use strict';
require('dotenv').config({path:require('node:path').join(__dirname,'../.env')});
const {readConfig}=require('./config'),{Store}=require('./store'),Rpc=require('./rpc'),Discovery=require('./discovery'),Stream=require('./stream'),{Trend}=require('./trend'),{parse}=require('./cross-dex'),{Jupiter}=require('./providers');
function publicConfig(c){const {jupiterKey,rpcUrl,wsUrl,...safe}=c;return safe;}
function main(){const c=readConfig();if(!c.jupiterKey)throw Error('JUPITER_API_KEY required');const store=new Store(c.dataDir),rpc=new Rpc(c),jupiter=new Jupiter(c),discovery=new Discovery(c,store,rpc,jupiter),trend=new Trend(c,store,discovery,jupiter),stream=new Stream(c,store);let subscribed=new Map(),stopping=false;const rejected={};store.log('session',{config:publicConfig(c),realTradingPossible:false});
 stream.on('transaction',r=>{try{for(const s of parse(r,subscribed,(m,t)=>discovery.usd(m,t),reason=>rejected[reason]=(rejected[reason]||0)+1))trend.onSwap(s);}catch{rejected.parser_error=(rejected.parser_error||0)+1;}});stream.on('connection',ok=>{trend.connection(ok);store.log('connection',{connected:ok});});stream.on('removed',pool=>trend.remove(pool,'candidate_subscription_removed'));stream.start();
 const sync=()=>{const next=discovery.active();for(const p of store.data.positions)if(subscribed.has(p.pool))next.set(p.pool,subscribed.get(p.pool));subscribed=next;stream.setPools([...next.keys()]);};
 const tick=setInterval(()=>{trend.tick();sync();discovery.tick().then(()=>{if(!stopping)sync();}).catch(()=>store.log('discovery_error'));},1000),quotes=setInterval(()=>trend.quotes().catch(()=>store.log('quote_cycle_error')),c.quotePollMs),save=setInterval(()=>store.save({...trend.view(),subscriptions:stream.active.size,parserRejected:rejected}),5000),health=setInterval(()=>{const v={...trend.view(),subscriptions:stream.active.size,parserRejected:{...rejected}};store.log('health',v);console.log(JSON.stringify({type:'trend_health',mode:'shadow_only',connected:v.connected,selected:v.discovery.selected,subscriptions:v.subscriptions,entries:v.counts.entries,positions:store.data.positions.length}));},60000);
 const stop=()=>{if(stopping)return;stopping=true;stream.stop();clearInterval(tick);clearInterval(quotes);clearInterval(save);clearInterval(health);trend.gap('process_shutdown');store.close();process.exit(0);};process.on('SIGTERM',stop);process.on('SIGINT',stop);console.log('Selected-pool momentum: SHADOW ONLY; Dex discovery / Helius flow / Jupiter quotes.');
}
if(require.main===module)try{main();}catch{console.error('Shadow startup failed; check configuration and lock.');process.exitCode=1;}
module.exports={main,publicConfig};
