'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
function atomicJSON(file,data){fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file+'.tmp',JSON.stringify(data),{mode:0o600});fs.renameSync(file+'.tmp',file);}
class Store{
 constructor(dir){this.dir=dir;fs.mkdirSync(dir,{recursive:true});this.file=path.join(dir,'trend-state.json');this.lock=path.join(dir,'trend.lock');if(fs.existsSync(this.lock)){const pid=Number(fs.readFileSync(this.lock,'utf8'));if(!Number.isInteger(pid)||pid<1)throw new Error('Invalid lock');try{process.kill(pid,0);throw new Error('Already running');}catch(e){if(e.code!=='ESRCH')throw e;}fs.unlinkSync(this.lock);}fs.writeFileSync(this.lock,String(process.pid),{flag:'wx',mode:0o600});this.data=fs.existsSync(this.file)?JSON.parse(fs.readFileSync(this.file,'utf8')):{schema:1,ages:{},streamDays:{},positions:[],totals:{closed:0,wins:0,net:0,unknown:0}};if(this.data.schema!==1)throw new Error('Invalid trend state');this.runId=crypto.randomUUID();this.events=[];for(const p of this.data.positions){this.log('shadow_unknown',{...p,reason:'process_restart'});this.data.totals.unknown++;}this.data.positions=[];if(this.data.strategy!=="selected_pool_momentum_v2"){this.data.previousTotals=this.data.totals;this.data.totals={closed:0,wins:0,net:0,unknown:0};this.data.strategy="selected_pool_momentum_v2";this.log("strategy_boundary",{previousTotals:this.data.previousTotals});}}
 log(type,fields={}){const r={...fields,type,at:fields.at??Date.now(),schema:1,strategy:this.data.strategy||'old_pool_momentum_v1',runId:this.runId};fs.appendFileSync(path.join(this.dir,'trend-'+new Date(r.at).toISOString().slice(0,10)+'.jsonl'),JSON.stringify(r)+'\n',{mode:0o600});this.events.push(r);if(this.events.length>500)this.events.shift();}
 save(view=this.lastView||{}){this.lastView=view;atomicJSON(this.file,this.data);atomicJSON(path.join(this.dir,'dashboard.json'),{at:Date.now(),mode:'shadow_only',strategy:'selected_pool_momentum_v2',...view,totals:this.data.totals,positions:this.data.positions,events:this.events.slice().reverse()});}
 close(){this.save();fs.unlinkSync(this.lock);}
}
module.exports={Store,atomicJSON};
