'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{EventEmitter}=require('node:events');
const {readConfig,WSOL,PUMP}=require('../src/config'),Discovery=require('../src/discovery'),{ReadApi,Jupiter}=require('../src/providers'),{parseNormalized,layouts}=require('../src/cross-dex'),Stream=require('../src/stream'),{Trend}=require('../src/trend'),{publicConfig}=require('../src/index');
const mint='Bfsp4Y4VGadXAoeH2ktiaKXQLcZaSuzmFbaS6tPupump',pool='4BQ6ATUt26GFdiYQfht23iwfKyYD9D7XbL5ATqNGk3xK',day=86400000;
const cfg=()=>readConfig({JUPITER_API_KEY:'private-test'});
function setup(){const events=[],store={data:{positions:[],streamDays:{},ages:{},totals:{closed:0,wins:0,net:0,unknown:0}},log:(type,r)=>events.push({type,...r})},c=cfg();return {c,store,events};}
test('first pool age inclusive 1–14 days, strict FDV, no migration or pairCreatedAt fallback',()=>{const {c,store}=setup(),d=new Discovery(c,store,{},{}),now=20*day,p={chainId:'solana',pairAddress:pool,baseToken:{address:mint},quoteToken:{address:WSOL},fdv:30001,pairCreatedAt:0},meta=days=>({id:mint,firstPool:{createdAt:new Date(now-days*day).toISOString()}});assert.ok(d.eligible(p,meta(1),now));assert.ok(d.eligible(p,meta(14),now));for(const days of [.99,14.01])assert.equal(d.eligible(p,meta(days),now),false);for(const fdv of [null,30000,NaN])assert.equal(d.eligible({...p,fdv},meta(2),now),false);assert.equal(d.eligible(p,{id:mint},now),false);});
test('metadata can only enrich requested mints; provider extras cannot discover tokens',async()=>{const {c,store}=setup(),d=new Discovery(c,store,{}, {tokens:async()=>[{id:mint},{id:pool}]});await d.tokens([mint]);assert.ok(d.metadata.has(mint));assert.equal(d.metadata.has(pool),false);assert.deepEqual(d.catalog,{});});
test('expired FDV checks or age remove admission; SOL conversion expires',()=>{const {c,store}=setup(),d=new Discovery(c,store,{},{}),now=Date.now();d.selected.set(pool,{mint,checkedAt:now,firstPoolAt:now-2*day});assert.ok(d.old(pool,mint,now));assert.equal(d.old(pool,mint,now+c.metadataTtlMs+1),false);d.metadata.set(WSOL,{usdPrice:100,fetchedAt:now});assert.equal(d.usd(WSOL,now+120001),null);});
for(const spec of layouts)test(spec.name+' parses one swap, rejects LP and repeated swaps',()=>{const acc=Array(20).fill('other');acc[spec.pool]=pool;acc[spec.user]='buyer';acc[spec.vaults[0]]='vaultA';acc[spec.vaults[1]]='vaultB';const bal=(i,m,amount)=>({accountIndex:i,mint:m,uiTokenAmount:{amount:String(amount),decimals:i===1?9:6}}),ix={program:spec.program,accounts:acc,data:Buffer.from(spec.tags[0])},tx={keys:['vaultA','vaultB'],signature:'sig',slot:1,instructions:[ix],meta:{preTokenBalances:[bal(0,mint,1000000),bal(1,WSOL,1000000000)],postTokenBalances:[bal(0,mint,900000),bal(1,WSOL,1100000000)]}},selected=new Map([[pool,{mint,quoteMint:WSOL,owner:spec.program}]]),price=()=>100;let r=parseNormalized(tx,selected,price,100);assert.equal(r.length,1);assert.equal(r[0].side,'buy');assert.equal(r[0].quoteSol,.1);assert.equal(r[0].quoteUsd,10);assert.equal(r[0].price,1e-6);assert.equal(parseNormalized({...tx,instructions:[ix,ix]},selected,price).length,0);assert.equal(parseNormalized({...tx,instructions:[{...ix,data:Buffer.alloc(8)}]},selected,price).length,0);assert.equal(parseNormalized(tx,selected,()=>null).length,0);});
test('API endpoint whitelist rejects swap execution and foreign URLs before network',async()=>{let calls=0;const p=new ReadApi('api.jup.ag',10,'key',async()=>{calls++;});for(const path of ['/swap/v2/execute','/swap/v1/swap','https://evil.test/'])await assert.rejects(p.get(path),/allowlist/);assert.equal(calls,0);const s=JSON.stringify(publicConfig(cfg()));assert.ok(!s.includes('private-test'));assert.ok(!s.includes('rpcUrl'));});
test('quote preserves raw integer precision, shares concurrent arms and excludes credentials',async()=>{const c=cfg();let calls=0;const j=new Jupiter(c,async()=>{calls++;await new Promise(r=>setTimeout(r,5));return {ok:true,status:200,text:async()=>JSON.stringify({inputMint:WSOL,outputMint:mint,inAmount:'50000000',outAmount:'9007199254740993123',otherAmountThreshold:'9007199254740993000',priceImpactPct:'0.2',routePlan:[{swapInfo:{ammKey:pool,label:'test'},percent:100}],contextSlot:1})};});const [a,b]=await Promise.all([j.buy(mint),j.buy(mint)]);assert.equal(calls,1);assert.equal(a.minimumOut,'9007199254740993000');assert.deepEqual(a,b);assert.ok(!JSON.stringify(a).includes('private-test'));});
test('daily budget or empty candidate list never starts global stream',()=>{class Sock{constructor(){throw Error('must not connect');}}const {c,store}=setup(),s=new Stream(c,store,Sock);s.start();s.setPools([]);s.stop();store.data.streamDays[new Date().toISOString().slice(0,10)]=c.maxBytesPerDay;const t=new Stream(c,store,Sock);t.setPools([pool]);t.start();t.stop();});
test('subscription delta keeps existing history, unsubscribe acknowledged, only pool filters',()=>{class Sock extends EventEmitter{constructor(){super();this.readyState=1;this.sent=[];Sock.instance=this;}send(s){this.sent.push(JSON.parse(s));}terminate(){}close(){}ping(){}}const {c,store}=setup(),s=new Stream(c,store,Sock);s.setPools([pool]);s.start();const ws=Sock.instance;ws.emit('open');assert.deepEqual(ws.sent[0].params[0].accountInclude,[pool]);ws.emit('message',Buffer.from(JSON.stringify({id:1,result:77})));s.setPools([pool,mint]);assert.equal(ws.sent.length,2);ws.emit('message',Buffer.from(JSON.stringify({id:2,result:78})));s.setPools([mint]);assert.equal(ws.sent[2].method,'transactionUnsubscribe');ws.emit('message',Buffer.from(JSON.stringify({id:3,result:true})));assert.equal(s.active.has(pool),false);assert.equal(s.active.get(mint),78);s.stop();});
test('inflight entry quote cannot create a position after disconnect',async()=>{const {c,store}=setup();let release;const j={buy:()=>new Promise(r=>release=r)},d={old:()=>true,usablePrice:()=>({usd:100})},t=new Trend(c,store,d,j);t.connected=true;t.pending.set('key',{id:'p',mint,pool,at:Date.now()-1000});const job=t.quotes();await new Promise(r=>setImmediate(r));t.gap('disconnected');release({});await job;assert.equal(store.data.positions.length,0);});
test('delayed Jupiter entry and independent arms use quote amount, no reserve approximation',async()=>{const {c,store}=setup(),now=Date.now(),j={buy:async()=>({requestedAt:now,receivedAt:now,minimumOut:'1234567890123456789',priceImpactPct:.1})},d={old:()=>true,usablePrice:()=>({usd:100})},t=new Trend(c,store,d,j);t.connected=true;t.pools.set(pool,{last:now,events:[{receivedAt:now,side:'buy',quoteSol:1}],quote:{price:2}});for(const arm of ['a','b'])t.pending.set(arm,{id:arm,mint,pool,at:now-1000,level:1,arm});await t.quotes();assert.equal(store.data.positions.length,2);assert.equal(store.data.positions[0].raw,'1234567890123456789');});
test('trailing sell needs post-signal quote; cost is deducted without duplicate swap fees',async()=>{const {c,store,events}=setup(),now=Date.now(),j={sell:async()=>({requestedAt:Date.now(),minimumOut:'110000000'})},t=new Trend(c,store,{},j);t.connected=true;t.pools.set(pool,{last:now,events:[],quote:{price:2}});const p={id:'p',mint,pool,arm:'a',raw:'100000',cost:.1,openedAt:now-5000,lastAt:now,highNet:30,armed:true,exit:{arm:20,drop:8},level:1};store.data.positions=[p];await t.quotes();assert.equal(p.reason,'trailing_net_value');assert.equal(store.data.totals.closed,0);p.exitAt=Date.now()-1000;await t.quotes();assert.equal(store.data.totals.closed,1);assert.ok(Math.abs(store.data.totals.net-(.11-c.networkSol-.1))<1e-12);assert.ok(events.some(e=>e.type==='shadow_exit'&&e.quote));});
test('failed sell quote never records zero PnL, timeout remains unknown',async()=>{const {c,store}=setup(),t=new Trend(c,store,{}, {sell:async()=>{throw Error('unavailable');}});t.connected=true;store.data.positions=[{id:'p',mint,pool,raw:'1',lastAt:Date.now()-16000}];await t.quotes();t.tick();assert.equal(store.data.totals.closed,0);assert.equal(store.data.totals.unknown,1);});
